# Copyright (c) Quectel Wireless Solution, Co., Ltd.All Rights Reserved.
 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
 
#     http://www.apache.org/licenses/LICENSE-2.0
 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from usr.drivers.LB2209conf import *

DEMO_MODE = True
USE_DEVBOARD = False

# 主线程消息定义
MSG_MMI_UPDATE_UI = 0
MSG_MMI_SET_NAVI_INFO = 1
MSG_MMI_NET_EVENT = 2
MSG_MMI_MAX = 3
# MSG_MMI_SET_SPEED = 1
# MSG_MMI_UNLOCK = 2
# MSG_MMI_LOCK = 3


NETWORK_EVENT_NO_SIM = 1
NETWORK_EVENT_NETWORK_REG_FAIL = 2
NETWORK_EVENT_DATA_CONNECTED = 3
NETWORK_EVENT_DATA_FAIL = 4

UI_TYPE_CONTROLLER = 0
UI_TYPE_BMS = 1
# MSG_MMI_IND_MOTOR_MAX_CURRENT = 3
# MSG_MMI_IND_MOTOR_SN_0_7 = 4
# MSG_MMI_IND_MOTOR_SN_8_19 = 5
# MSG_MMI_IND_MOTOR_INFO_1 = 6
# MSG_MMI_IND_MOTOR_INFO_2 = 7


# UI线程消息定义
MSG_UI_SET_SPEED = 0
MSG_UI_SET_CURRENT = 1
MSG_UI_SET_BATTERY = 2
MSG_UI_SET_GEAR = 3
MSG_UI_SET_TRIP = 4
MSG_UI_SET_LEFTKM = 5
MSG_UI_SET_TIME = 6
MSG_UI_SET_READY = 7
MSG_UI_SET_MOBILE_SIGNAL = 8
MSG_UI_SET_GPS = 9
MSG_UI_SET_BT = 10
MSG_UI_SET_LIGHT_LEFT = 11
MSG_UI_SET_LIGHT_RIGHT = 12
MSG_UI_SET_LIGHT_FAR = 13
MSG_UI_SET_LIGHT_NEAR = 14
MSG_UI_SET_LIGHT_AUTO = 15
MSG_UI_SET_LIGHT_SMALL = 16
MSG_UI_SET_LIGHT_DOUBLEFLASH = 17
MSG_UI_SET_AUTO_SPEED = 18
MSG_UI_SET_WARNING = 19
MSG_UI_SET_BATT_WARNING = 20
MSG_UI_SET_ECO = 21
MSG_UI_SET_CHARGING = 22
MSG_UI_SET_NOT_SIT = 23
MSG_UI_SET_BIANCHENG = 24
MSG_UI_SET_UNBIND = 25
MSG_UI_SET_NAVI_INFO = 26
MSG_UI_SET_ODO = 27
MSG_UI_HIDE_NAVI = 28
MSG_UI_MAX = 29

# 串口模块消息定义
MSG_SERIAL_READ = 0
MSG_SERIAL_WRITE = 1
MSG_SERIAL_WRITE_RAW = 2
MSG_SERIAL_MAX = 3

# cloud模块消息定义
MSG_CLOUD_PUBLISH = 0
MSG_CLOUD_PROCESS_CMD = 1
MSG_CLOUD_MAX = 2

# CMD_TYPE_C_M_485 = b'OP485CM'
# CMD_TYPE_M_C_485 = b'485DATA'
# CMD_TYPE_BACKLIGHT = b'OPSLBLL'

CMD_TYPE_M_C_INFO = b'REPINFO'

CMD_TYPE_C_M_UPDATE_MCU = b'OPMCUFC'
CMD_TYPE_C_M_433 = b'433STDY'
CMD_TYPE_C_M_SET_LED_LOOP = b'LOOKCAR'
CMD_TYPE_C_M_LOCK_CONFIG = b'CARPCFG'
CMD_TYPE_C_M_CCTLOCK = b'CCTLOCK'
CMD_TYPE_C_M_CTRL = b'CTRLSET'
CMD_TYPE_C_M_CHARGE = b'CHARSET'
CMD_TYPE_C_M_NFC = b'NFCCTRL'
CMD_TYPE_C_M_SET_LED = b'CTRLLED'
CMD_TYPE_C_M_BACKLIGHT = b'OPSLBLL'
CMD_TYPE_C_M_REALDAT = b'REALDAT'


# 解锁状态
MODE_UNLOCK = 0 # 解锁状态
MODE_LOCK = 1 # 上锁状态
MODE_READY_TO_UNLOCK = 2 # 无感解锁后等待确认状态
MODE_READY_TO_LOCK = 3 # 关电后等待无感锁车状态

# 蓝牙模式
BT_MODE_NORMAL = 0 # 解锁后等待手机连接的状态
BT_MODE_SCAN_TO_LOCK = 1 # 关电后等待无感锁车状态
BT_MODE_SCAN_TO_UNLOCK = 2 #锁车后等待无感解锁状态
BT_MODE_STOP = 3 # 没开无感解锁，锁车后关闭蓝牙

# 蓝牙开关状态
BT_STATUS_OFF = 0
BT_STATUS_NOT_CONNECTED = 1
BT_STATUS_CONNECTED = 2

# 线程号
THREAD_ID_MAIN = 1
THREAD_ID_UI = 2
THREAD_ID_BT = 3
THREAD_ID_GPS = 4
THREAD_ID_SERIAL = 5
THREAD_ID_MQTT_RECV = 6
THREAD_ID_MQTT_SEND = 7
THREAD_ID_OTA = 8
THREAD_ID_KEY = 9
THREAD_ID_FTUI = 10
THREAD_ID_SERIAL_READ = 11
THREAD_ID_NETWORK = 12
THREAD_ID_UI_DEMO = 13